/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS.view;

import UAS.ControllerTeman.ControllerTeman;
import UAS.Model.Modelteman;
import UAS.Util.Koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ViewTeman extends javax.swing.JFrame {
    Koneksi koneksi = new Koneksi();
    ControllerTeman ct= new ControllerTeman();
    Modelteman mt= new Modelteman();
    

    /**
     * Creates new form ViewTeman
     */
    public ViewTeman() {
        initComponents();
        dataTable();
        
    }
    private void Baru(){
        btn_baru.setEnabled(false);
        btn_ubah.setEnabled(false);
        btn_simpan.setEnabled(true);
        btn_hapus.setEnabled(true);
        Jt_nama.setEditable(true);
        Jt_nope.setEditable(true);
        jt_email.setEditable(true);
        bersih();
    }
    private void bersih2(){
        btn_baru.setEnabled(true);
        btn_simpan.setEnabled(false);
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
        Jt_nama.setEditable(false);
        Jt_nope.setEditable(true);
        jt_email.setEditable(true);
        bersih();
    }
    private void bersih(){
         btn_simpan.setEnabled(false);
        Jt_nama.setEditable(true);
        Jt_nope.setEditable(true);
        jt_email.setEditable(true);
        btn_hapus.setEnabled(true);
        btn_ubah.setEnabled(true);
    }
    private void dataTable(){
        koneksi.koneksiDatabase();
        DefaultTableModel tabel = new DefaultTableModel();

        tabel.addColumn("ID");
        tabel.addColumn("Nama Teman");
        tabel.addColumn("Nope");
        tabel.addColumn("Email");
        
        tbl_kesalahan.setModel(tabel);
        try {
            String sql ="select * from tbl_teman";
            ResultSet res =koneksi.state.executeQuery(sql);
            while (res.next()){
                tabel.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("Nama"),
                    res.getString("Nope"),
                    res.getString("Email")
                });
                tbl_kesalahan.setModel(tabel);
                }
        } catch (SQLException eer) {
            System.err.println("SQlException:"+eer.getMessage());
            
        }
        
        

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Jt_id = new javax.swing.JTextField();
        Jt_nama = new javax.swing.JTextField();
        Jt_nope = new javax.swing.JTextField();
        jt_email = new javax.swing.JTextField();
        btn_baru = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_bersih = new javax.swing.JButton();
        btn_tutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kesalahan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("nope");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        Jt_id.setEnabled(false);
        getContentPane().add(Jt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 190, -1));
        getContentPane().add(Jt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 190, -1));
        getContentPane().add(Jt_nope, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 190, -1));

        jt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(jt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 190, -1));

        btn_baru.setText("Baru");
        btn_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruActionPerformed(evt);
            }
        });
        getContentPane().add(btn_baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        btn_ubah.setText("Ubah");
        btn_ubah.setEnabled(false);
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        btn_hapus.setText("Hapus");
        btn_hapus.setEnabled(false);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        btn_bersih.setText("Bersih");
        btn_bersih.setEnabled(false);
        btn_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        btn_tutup.setText("Tutup");
        btn_tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tutupActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        tbl_kesalahan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_kesalahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kesalahanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_kesalahan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruActionPerformed
        // TODO add your handling code here:
        Baru();
        
    }//GEN-LAST:event_btn_baruActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(Jt_id.getText());
            mt.setId(id);
            ct.hapusData(mt);
            dataTable();
            bersih2();
            bersih();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this,"Harap masukan nama teman");
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bersihActionPerformed

    private void jt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_emailActionPerformed

    private void tbl_kesalahanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kesalahanMouseClicked
        // TODO add your handling code here:
        try {
            int baris = tbl_kesalahan.getSelectedRow();
            Jt_id.setText(tbl_kesalahan.getValueAt(baris,0).toString());
             Jt_nama.setText(tbl_kesalahan.getValueAt(baris,1).toString());
              Jt_nope.setText(tbl_kesalahan.getValueAt(baris,2).toString());
               jt_email.setText(tbl_kesalahan.getValueAt(baris,3).toString());
            
        } catch (Exception e) {
            System.err.println("eror:"+e);
        }
    
        
        
    }//GEN-LAST:event_tbl_kesalahanMouseClicked

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        try {
            String Nama =Jt_nama.getText();
            String Nope =Jt_nope.getText();
            String Email=jt_email.getText();
            mt.setNama(Nama);
            mt.setNope(Nope);
            mt.setEmail(Email);
            ct.simpanData(mt);
            dataTable();
            bersih2();
          } catch (NumberFormatException e) {
              JOptionPane.showMessageDialog(this,"Harap masukan angka");
              
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try {
            int id =Integer.parseInt(Jt_id.getText());
            String Nama = Jt_nama.getText();
            String Nope = Jt_nope.getText();
            String Email= jt_email.getText();
            mt.setId(id);
            mt.setEmail(Email);
            mt.setNama(Nama);
            mt.setNope(Nope);
            ct.ubahData(mt);
            
            bersih();
            dataTable();
            
            
        } catch (NullPointerException e) {
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_tutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tutupActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_tutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTeman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jt_id;
    private javax.swing.JTextField Jt_nama;
    private javax.swing.JTextField Jt_nope;
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btn_bersih;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tutup;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jt_email;
    private javax.swing.JTable tbl_kesalahan;
    // End of variables declaration//GEN-END:variables
}
