/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS.view;


import UAS.Util.Koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class viewCariTeman extends javax.swing.JFrame {

    /**
     * Creates new form viewCariTeman
     */
    public viewCariTeman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Jt_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cari");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        Jt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jt_cariActionPerformed(evt);
            }
        });
        Jt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Jt_cariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Jt_cariKeyReleased(evt);
            }
        });
        getContentPane().add(Jt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 11, 275, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 390, -1));

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jt_cariActionPerformed
        // TODO add your handling code here:
        DefaultTableModel table = new DefaultTableModel();
        String Nama = Jt_cari.getText();
        
        table.addColumn("id");
        table.addColumn("Nama");
        table.addColumn("nope");
        table.addColumn("Email");
        
        jTable1.setModel(table);
        
        try {
            Koneksi a = new Koneksi();
            a.koneksiDatabase();
            String queryTampil ="select * from tbl_teman where nama like '%"+Nama+"%'";  
            
            ResultSet res = a.state.executeQuery(queryTampil);
            
            while (res.next());
            table.addRow(new Object[]{
                 res.getInt("id"), res.getString("Nama"), res.getString("nope"),res.getString("Email")  
            });
            jTable1.setModel(table);
            
            
            
            
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_Jt_cariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Jt_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jt_cariKeyPressed
        // TODO add your handling code here:
       
           
            
            
            
    }//GEN-LAST:event_Jt_cariKeyPressed

    private void Jt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jt_cariKeyReleased
        // TODO add your handling code here:
          DefaultTableModel table = new DefaultTableModel();
        String Nama = Jt_cari.getText();
        
        table.addColumn("id");
        table.addColumn("Nama");
        table.addColumn("nope");
        table.addColumn("Email");
        
        jTable1.setModel(table);
        try {
             Koneksi a = new Koneksi();
            a.koneksiDatabase();
            String queryTampil ="select * from tbl_teman where nama like '%"+Nama+"%'";  
            
            ResultSet res = a.state.executeQuery(queryTampil);
            
            while (res.next());
            table.addRow(new Object[]{
                 res.getInt("id"), res.getString("Nama"), res.getString("nope"),res.getString("Email")  
            });
            jTable1.setModel(table);
        } catch (SQLException e) {
        }
        
    }//GEN-LAST:event_Jt_cariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCariTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCariTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCariTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCariTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCariTeman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jt_cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
